version: "3.9"

services:
    db:
        image: mysql:8
        container_name: otokse_mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: v2
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

    backend:
        build: ./backend
        container_name: otokse_laravel_app
        restart: unless-stopped
        expose:
            - "80" # expose only internal port for reverse proxy
        environment:
            APP_NAME: Laravel
            APP_ENV: production
            APP_DEBUG: false
            APP_TIMEZONE: Asia/Dubai
            APP_URL: https://otokse_service.lidta.com
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: v2
            DB_USERNAME: root
            DB_PASSWORD: root
            SESSION_DRIVER: database
            CACHE_STORE: database
            QUEUE_CONNECTION: database
        depends_on:
            - db
        volumes:
            - ./backend:/var/www/html

    frontend:
        build: ./frontend
        container_name: otokse_react_app
        restart: unless-stopped
        expose:
            - "80" # internal port only, reverse proxy handles public access
        environment:
            REACT_APP_API_URL: https://otokse_service.lidta.com/api
        depends_on:
            - backend
        volumes:
            - ./frontend:/app

volumes:
    db_data:
