services:
    - type: web
      name: laravel-api
      env: php
      buildCommand: |
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan migrate --force
          php artisan db:seed --force
          php artisan storage:link
      startCommand: php artisan serve --host=0.0.0.0 --port=10000
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          # Add DB credentials here if you want, or add manually on Render dashboard
